config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/new'

  get 'users/show'
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match '/checkout' => 'reservations#checkout', :via => :post, :as => :checkout
  match '/return' => 'reservations#return', :via => :post, :as => :return
  resources :reservations
  resources :cars
  root 'application#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = current_user.admin? || current_user.superadmin? ? Reservation.all : Reservation.where('user_id = ?', current_user.id)
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @user_id = current_user.id
    @car_id = params[:car_id]
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.checkout_time > DateTime.now.advance({days:7})
      raise 'Reservations are allowed only till upcoming 7 days'
    end
    if @reservation.return_time < @reservation.checkout_time.advance({hours: 1}) or
        @reservation.return_time > @reservation.checkout_time.advance({hours:10})
      raise 'Reservation below 1 hour and more than 10 hours is not allowed'
    end
    if User.find(@reservation.user_id).has_reserved?
      raise 'Can not have more than one reservations'
    end
    @reservation.reserved = true
    respond_to do |format|
      if @reservation.save
        @car = Car.find(params[:reservation][:car_id])
        @car.status = 'reserved'
        @car.save
        @user = User.find(params[:reservation][:user_id])
        @user.has_reserved = true
        @user.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @car = Car.find(@reservation.car_id)
    @car.status = 'available'
    @car.save
    @user = User.find(@reservation.user_id)
    @user.has_reserved = false
    @user.save
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def checkout
    @reservation = Reservation.find(params[:reservation_id])
    @reservation.checked_out = true
    @reservation.save
    @car = Car.find(@reservation.car_id)
    @car.status = 'checked_out'
    @car.save
  end

  def return
    @reservation = Reservation.find(params[:reservation_id])
    @reservation.checked_out = false
    @reservation.save
    @car = Car.find(@reservation.car_id)
    @car.status = 'available'
    @car.save
    @user = User.find(@reservation.user_id)
    @user.has_reserved = false
    @user.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:id, :user_id, :car_id, :checkout_time, :return_time, :checked_out, :reserved)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if is_user_admin_or_superadmin? %>
        <div class="field">
          <%= f.label :user_id %>
          <%= f.text_field :user_id, id: :reservation_user_id, :value => @user_id %>
        </div>
        <div class="field">
          <%= f.label :car_id %>
          <%= f.text_field :car_id, id: :reservation_car_id, :value => @car_id %>
        </div>
    <% else %>
        <%= f.hidden_field :user_id, :value => @user_id%>
        <%= f.hidden_field :car_id, :value => @car_id%>
    <% end %>

  <div class="field">
    <%= f.label :checkout_time %>
    <%= f.datetime_select :checkout_time %>
  </div>

  <div class="field">
    <%= f.label :return_time %>
    <%= f.datetime_select :return_time %>
  </div>

    <% if is_user_admin_or_superadmin? %>
  <div class="field">
    <%= f.label :checked_out %>
    <%= f.check_box :checked_out %>
  </div>

  <div class="field">
    <%= f.label :reserved %>
    <%= f.check_box :reserved %>
  </div>
    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Cars', cars_path %>

<h1>Reservations</h1>

<table>
  <thead>
  <tr>
    <th>Checkout time</th>
    <th>Return time</th>
    <th>Checked out</th>
    <th>Reserved</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.checkout_time %></td>
        <td><%= reservation.return_time %></td>
        <td><%= reservation.checked_out %></td>
        <td><%= reservation.reserved %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% if is_user_admin_or_superadmin? %>
            <% if reservation.checked_out? %>
                <td><%= link_to 'Return', return_path(:reservation_id => reservation), method: :post %></td>
            <% else %>
                <td><%= link_to 'Check Out', checkout_path(:reservation_id => reservation), method: :post %></td>
            <% end %>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Checkout time:</strong>
  <%= @reservation.checkout_time %>
</p>

<p>
  <strong>Return time:</strong>
  <%= @reservation.return_time %>
</p>

<p>
  <strong>Checked out:</strong>
  <%= @reservation.checked_out %>
</p>

<p>
  <strong>Reserved:</strong>
  <%= @reservation.reserved %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>