config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/new'

  get 'users/show'
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match '/checkout' => 'reservations#checkout', :via => :post, :as => :checkout
  match '/return' => 'reservations#return', :via => :post, :as => :return
  resources :reservations
  resources :cars
  root 'application#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  validates_inclusion_of :status, in: ['available', 'checked_out', 'reserved'], default: 'available'
  validates_length_of :registration_number, is: 7, uniqueness: true
  has_many :reservations

  def self.search(term)
    if term
      where('model LIKE ? OR manufacturer LIKE ? OR status LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%")
    else
      all
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.search(params[:term])
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:registration_number, :status, :model, :manufacturer, :rate, :term)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(car) do |f| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
  </div>

  <div class="field">
    <%= f.label :rate %>
    <%= f.text_field :rate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Reservations', reservations_path %>

<h1>Cars</h1>

<%= form_tag(cars_path, method: :get) do %>
    <%= text_field_tag :term, params[:term] %>
    <%= submit_tag 'Search', name: nil %>
<% end %>

<table>
  <thead>
  <tr>
    <th>Registration number</th>
    <th>Status</th>
    <th>Model</th>
    <th>Manufacturer</th>
    <th>Rate</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
      <tr>
        <td><%= car.registration_number %></td>
        <td><%= car.status %></td>
        <td><%= car.model %></td>
        <td><%= car.manufacturer %></td>
        <td><%= car.rate %></td>
        <td><%= link_to 'Show', car %></td>
        <% if is_user_admin_or_superadmin? %>
          <td><%= link_to 'Edit', edit_car_path(car) %></td>
          <td><%= link_to 'Destroy', car, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
        <% if car.status == 'available' %>
            <td><%= link_to 'Reserve', new_reservation_path(car_id: car.id)%></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<% if is_user_admin_or_superadmin? %>
    <%= link_to 'New Car', new_car_path %>
<% end %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p>
  <strong>Registration number:</strong>
  <%= @car.registration_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car.status %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.manufacturer %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @car.rate %>
</p>

<% if is_user_admin_or_superadmin? %>
  <%= link_to 'Edit', edit_car_path(@car) %> |
<% end %>
<%= link_to 'Back', cars_path %>