config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/new'

  get 'users/show'
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match '/checkout' => 'reservations#checkout', :via => :post, :as => :checkout
  match '/return' => 'reservations#return', :via => :post, :as => :return
  resources :reservations
  resources :cars
  root 'application#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/startup_page.html.erb
<% if user_signed_in? %>
    <h3>Welcome <%= current_user.email %> </h3>
    <%= link_to 'Edit Profile', edit_user_registration_path %>
    <%= link_to 'View All Cars', cars_path %>
    <% if is_user_admin_or_superadmin? %>
        <%= link_to 'View Users', users_index_path %>
        <%= link_to 'Create Admin', users_new_path %>
    <% else %>
        <%= link_to 'View Active Reservations', reservations_path %>
    <% end %>
<% else %>
    <h1>
      Welcome to the Car Rental App
    </h1>
    <%= link_to 'Login', new_user_session_path %>
    <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>